let rawData =
[
	{
		"title": "Twin Falls Idaho",
		"genre": "드라마",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "5",
		"us_gross": "9",
		"worldwide_gross": "10",
		"rotten_rating": "77",
		"imdb_rating": "7.1",
		"imdb_votes": "2,810"
	},
	{
		"title": "Beverly Hills Cop II",
		"genre": "액션",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "80년대",
		"rating": "19세이상",
		"budget": "200",
		"us_gross": "1536",
		"worldwide_gross": "2766",
		"rotten_rating": "46",
		"imdb_rating": "6.1",
		"imdb_votes": "29,712"
	},
	{
		"title": "Broken Arrow",
		"genre": "액션",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "650",
		"us_gross": "706",
		"worldwide_gross": "1483",
		"rotten_rating": "55",
		"imdb_rating": "5.8",
		"imdb_votes": "33,584"
	},
	{
		"title": "Batman",
		"genre": "액션",
		"creative_type": "영웅물",
		"source": "만화",
		"release": "80년대",
		"rating": "15세이상",
		"budget": "350",
		"us_gross": "2511",
		"worldwide_gross": "4113",
		"rotten_rating": "71",
		"imdb_rating": "7.6",
		"imdb_votes": "111,464"
	},
	{
		"title": "Copycat",
		"genre": "스릴러",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "200",
		"us_gross": "320",
		"worldwide_gross": "320",
		"rotten_rating": "75",
		"imdb_rating": "6.5",
		"imdb_votes": "17,182"
	},
	{
		"title": "Ed Wood",
		"genre": "코미디",
		"creative_type": "각색",
		"source": "책",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "180",
		"us_gross": "58",
		"worldwide_gross": "58",
		"rotten_rating": "91",
		"imdb_rating": "8.1",
		"imdb_votes": "74,171"
	},
	{
		"title": "From Dusk Till Dawn",
		"genre": "호러",
		"creative_type": "판타지",
		"source": "없음",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "200",
		"us_gross": "257",
		"worldwide_gross": "257",
		"rotten_rating": "63",
		"imdb_rating": "7.1",
		"imdb_votes": "80,234"
	},
	{
		"title": "The First Wives Club",
		"genre": "코미디",
		"creative_type": "현대소설",
		"source": "책",
		"release": "90년대",
		"rating": "7세이상",
		"budget": "300",
		"us_gross": "1054",
		"worldwide_gross": "1814",
		"rotten_rating": "41",
		"imdb_rating": "5.6",
		"imdb_votes": "14,682"
	},
	{
		"title": "Home Alone 2: Lost in New York",
		"genre": "코미디",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "90년대",
		"rating": "7세이상",
		"budget": "200",
		"us_gross": "1735",
		"worldwide_gross": "3589",
		"rotten_rating": "21",
		"imdb_rating": "5.8",
		"imdb_votes": "51,408"
	},
	{
		"title": "Home Alone",
		"genre": "코미디",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "90년대",
		"rating": "7세이상",
		"budget": "150",
		"us_gross": "2857",
		"worldwide_gross": "4766",
		"rotten_rating": "47",
		"imdb_rating": "7",
		"imdb_votes": "79,080"
	},
	{
		"title": "Jack",
		"genre": "드라마",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "90년대",
		"rating": "15세이상",
		"budget": "450",
		"us_gross": "586",
		"worldwide_gross": "586",
		"rotten_rating": "17",
		"imdb_rating": "5.3",
		"imdb_votes": "17,267"
	},
	{
		"title": "JFK",
		"genre": "드라마",
		"creative_type": "각색",
		"source": "책",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "400",
		"us_gross": "704",
		"worldwide_gross": "2054",
		"rotten_rating": "83",
		"imdb_rating": "8",
		"imdb_votes": "59,684"
	},
	{
		"title": "Jumanji",
		"genre": "어드벤처",
		"creative_type": "판타지",
		"source": "책",
		"release": "90년대",
		"rating": "7세이상",
		"budget": "650",
		"us_gross": "1004",
		"worldwide_gross": "2627",
		"rotten_rating": "48",
		"imdb_rating": "6.4",
		"imdb_votes": "54,973"
	},
	{
		"title": "Kiss of Death",
		"genre": "드라마",
		"creative_type": "현대소설",
		"source": "영화",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "400",
		"us_gross": "149",
		"worldwide_gross": "149",
		"rotten_rating": "67",
		"imdb_rating": "7.6",
		"imdb_votes": "2,374"
	},
	{
		"title": "Alien³",
		"genre": "액션",
		"creative_type": "공상과학",
		"source": "없음",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "550",
		"us_gross": "549",
		"worldwide_gross": "1585",
		"rotten_rating": "37",
		"imdb_rating": "6.3",
		"imdb_votes": "78,860"
	},
	{
		"title": "Lone Star",
		"genre": "드라마",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "50",
		"us_gross": "129",
		"worldwide_gross": "129",
		"rotten_rating": "92",
		"imdb_rating": "7.6",
		"imdb_votes": "14,599"
	},
	{
		"title": "Menace II Society",
		"genre": "액션",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "35",
		"us_gross": "277",
		"worldwide_gross": "277",
		"rotten_rating": "85",
		"imdb_rating": "7.4",
		"imdb_votes": "14,807"
	},
	{
		"title": "Mary Reilly",
		"genre": "드라마",
		"creative_type": "역사소설",
		"source": "책",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "470",
		"us_gross": "57",
		"worldwide_gross": "63",
		"rotten_rating": "27",
		"imdb_rating": "5.5",
		"imdb_votes": "6,864"
	},
	{
		"title": "The Mighty Ducks",
		"genre": "코미디",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "90년대",
		"rating": "7세이상",
		"budget": "100",
		"us_gross": "507",
		"worldwide_gross": "507",
		"rotten_rating": "8",
		"imdb_rating": "5.9",
		"imdb_votes": "15,479"
	},
	{
		"title": "The English Patient",
		"genre": "드라마",
		"creative_type": "역사소설",
		"source": "책",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "350",
		"us_gross": "787",
		"worldwide_gross": "2317",
		"rotten_rating": "83",
		"imdb_rating": "7.3",
		"imdb_votes": "54,484"
	},
	{
		"title": "Outbreak",
		"genre": "스릴러",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "500",
		"us_gross": "678",
		"worldwide_gross": "678",
		"rotten_rating": "59",
		"imdb_rating": "6.4",
		"imdb_votes": "33,192"
	},
	{
		"title": "The Phantom",
		"genre": "액션",
		"creative_type": "영웅물",
		"source": "만화",
		"release": "90년대",
		"rating": "7세이상",
		"budget": "450",
		"us_gross": "172",
		"worldwide_gross": "172",
		"rotten_rating": "43",
		"imdb_rating": "4.8",
		"imdb_votes": "9,477"
	},
	{
		"title": "The Scarlet Letter",
		"genre": "드라마",
		"creative_type": "역사소설",
		"source": "책",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "500",
		"us_gross": "103",
		"worldwide_gross": "103",
		"rotten_rating": "15",
		"imdb_rating": "4.6",
		"imdb_votes": "6,155"
	},
	{
		"title": "The Usual Suspects",
		"genre": "드라마",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "60",
		"us_gross": "233",
		"worldwide_gross": "233",
		"rotten_rating": "87",
		"imdb_rating": "8.7",
		"imdb_votes": "266,890"
	},
	{
		"title": "Serial Mom",
		"genre": "코미디",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "130",
		"us_gross": "78",
		"worldwide_gross": "78",
		"rotten_rating": "61",
		"imdb_rating": "6.4",
		"imdb_votes": "10,999"
	},
	{
		"title": "Speed",
		"genre": "액션",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "300",
		"us_gross": "1212",
		"worldwide_gross": "2832",
		"rotten_rating": "90",
		"imdb_rating": "2.6",
		"imdb_votes": "4,175"
	},
	{
		"title": "The Fan",
		"genre": "스릴러",
		"creative_type": "현대소설",
		"source": "책",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "550",
		"us_gross": "185",
		"worldwide_gross": "185",
		"rotten_rating": "40",
		"imdb_rating": "5.6",
		"imdb_votes": "20,640"
	},
	{
		"title": "Trainspotting",
		"genre": "드라마",
		"creative_type": "현대소설",
		"source": "책",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "31",
		"us_gross": "165",
		"worldwide_gross": "240",
		"rotten_rating": "89",
		"imdb_rating": "8.2",
		"imdb_votes": "150,483"
	},
	{
		"title": "Toy Story",
		"genre": "어드벤처",
		"creative_type": "아동소설",
		"source": "없음",
		"release": "90년대",
		"rating": "전체관람가",
		"budget": "300",
		"us_gross": "1917",
		"worldwide_gross": "3619",
		"rotten_rating": "100",
		"imdb_rating": "8.2",
		"imdb_votes": "151,143"
	},
	{
		"title": "Vampire in Brooklyn",
		"genre": "호러",
		"creative_type": "판타지",
		"source": "없음",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "140",
		"us_gross": "196",
		"worldwide_gross": "196",
		"rotten_rating": "11",
		"imdb_rating": "4.3",
		"imdb_votes": "8,200"
	},
	{
		"title": "A Walk on the Moon",
		"genre": "드라마",
		"creative_type": "역사소설",
		"source": "없음",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "140",
		"us_gross": "47",
		"worldwide_gross": "47",
		"rotten_rating": "74",
		"imdb_rating": "6.4",
		"imdb_votes": "4,125"
	},
	{
		"title": "Warriors of Virtue",
		"genre": "액션",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "90년대",
		"rating": "7세이상",
		"budget": "350",
		"us_gross": "64",
		"worldwide_gross": "64",
		"rotten_rating": "10",
		"imdb_rating": "4",
		"imdb_votes": "1,202"
	},
	{
		"title": "102 Dalmatians",
		"genre": "코미디",
		"creative_type": "아동소설",
		"source": "책",
		"release": "2000년대",
		"rating": "전체관람가",
		"budget": "850",
		"us_gross": "669",
		"worldwide_gross": "669",
		"rotten_rating": "30",
		"imdb_rating": "4.4",
		"imdb_votes": "7,147"
	},
	{
		"title": "16 Blocks",
		"genre": "액션",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "450",
		"us_gross": "368",
		"worldwide_gross": "655",
		"rotten_rating": "55",
		"imdb_rating": "6.7",
		"imdb_votes": "41,207"
	},
	{
		"title": "88 Minutes",
		"genre": "스릴러",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "300",
		"us_gross": "169",
		"worldwide_gross": "329",
		"rotten_rating": "5",
		"imdb_rating": "5.9",
		"imdb_votes": "31,205"
	},
	{
		"title": "Eight Below",
		"genre": "어드벤처",
		"creative_type": "현대소설",
		"source": "영화",
		"release": "2000년대",
		"rating": "7세이상",
		"budget": "400",
		"us_gross": "816",
		"worldwide_gross": "1206",
		"rotten_rating": "71",
		"imdb_rating": "7.3",
		"imdb_votes": "17,717"
	},
	{
		"title": "8 Mile",
		"genre": "드라마",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "410",
		"us_gross": "1167",
		"worldwide_gross": "2429",
		"rotten_rating": "74",
		"imdb_rating": "6.7",
		"imdb_votes": "55,877"
	},
	{
		"title": "A Bug's Life",
		"genre": "어드벤처",
		"creative_type": "판타지",
		"source": "없음",
		"release": "90년대",
		"rating": "전체관람가",
		"budget": "450",
		"us_gross": "1627",
		"worldwide_gross": "3631",
		"rotten_rating": "91",
		"imdb_rating": "7.3",
		"imdb_votes": "56,866"
	},
	{
		"title": "Absolute Power",
		"genre": "스릴러",
		"creative_type": "현대소설",
		"source": "책",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "500",
		"us_gross": "500",
		"worldwide_gross": "500",
		"rotten_rating": "46",
		"imdb_rating": "6.5",
		"imdb_votes": "20,154"
	},
	{
		"title": "All the King's Men",
		"genre": "드라마",
		"creative_type": "역사소설",
		"source": "책",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "550",
		"us_gross": "72",
		"worldwide_gross": "95",
		"rotten_rating": "11",
		"imdb_rating": "6",
		"imdb_votes": "11,994"
	},
	{
		"title": "Alfie",
		"genre": "코미디",
		"creative_type": "현대소설",
		"source": "영화",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "400",
		"us_gross": "133",
		"worldwide_gross": "351",
		"rotten_rating": "49",
		"imdb_rating": "6.1",
		"imdb_votes": "20,769"
	},
	{
		"title": "Alien",
		"genre": "호러",
		"creative_type": "공상과학",
		"source": "없음",
		"release": "80년대 이전",
		"rating": "19세이상",
		"budget": "90",
		"us_gross": "809",
		"worldwide_gross": "2036",
		"rotten_rating": "97",
		"imdb_rating": "8.5",
		"imdb_votes": "180,387"
	},
	{
		"title": "Almost Famous",
		"genre": "코미디",
		"creative_type": "각색",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "600",
		"us_gross": "325",
		"worldwide_gross": "473",
		"rotten_rating": "88",
		"imdb_rating": "8",
		"imdb_votes": "94,424"
	},
	{
		"title": "Bruce Almighty",
		"genre": "코미디",
		"creative_type": "판타지",
		"source": "없음",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "810",
		"us_gross": "2427",
		"worldwide_gross": "4850",
		"rotten_rating": "48",
		"imdb_rating": "6.6",
		"imdb_votes": "92,494"
	},
	{
		"title": "Angels & Demons",
		"genre": "스릴러",
		"creative_type": "현대소설",
		"source": "책",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "1500",
		"us_gross": "1333",
		"worldwide_gross": "4859",
		"rotten_rating": "35",
		"imdb_rating": "6.7",
		"imdb_votes": "60,114"
	},
	{
		"title": "The Animal",
		"genre": "코미디",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "220",
		"us_gross": "557",
		"worldwide_gross": "557",
		"rotten_rating": "30",
		"imdb_rating": "4.6",
		"imdb_votes": "18,601"
	},
	{
		"title": "Anna and the King",
		"genre": "드라마",
		"creative_type": "각색",
		"source": "책",
		"release": "90년대",
		"rating": "15세이상",
		"budget": "750",
		"us_gross": "392",
		"worldwide_gross": "392",
		"rotten_rating": "51",
		"imdb_rating": "6.5",
		"imdb_votes": "14,881"
	},
	{
		"title": "Australia",
		"genre": "드라마",
		"creative_type": "역사소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "780",
		"us_gross": "495",
		"worldwide_gross": "2074",
		"rotten_rating": "54",
		"imdb_rating": "6.8",
		"imdb_votes": "38,089"
	},
	{
		"title": "Away We Go",
		"genre": "코미디",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "210",
		"us_gross": "94",
		"worldwide_gross": "101",
		"rotten_rating": "66",
		"imdb_rating": "7.3",
		"imdb_votes": "14,929"
	},
	{
		"title": "Baby Boy",
		"genre": "드라마",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "160",
		"us_gross": "287",
		"worldwide_gross": "287",
		"rotten_rating": "69",
		"imdb_rating": "6.1",
		"imdb_votes": "4,485"
	},
	{
		"title": "Body of Lies",
		"genre": "스릴러",
		"creative_type": "현대소설",
		"source": "책",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "675",
		"us_gross": "393",
		"worldwide_gross": "1083",
		"rotten_rating": "52",
		"imdb_rating": "7.2",
		"imdb_votes": "53,921"
	},
	{
		"title": "Bee Movie",
		"genre": "코미디",
		"creative_type": "아동소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "7세이상",
		"budget": "1500",
		"us_gross": "1266",
		"worldwide_gross": "2875",
		"rotten_rating": "51",
		"imdb_rating": "6.3",
		"imdb_votes": "30,575"
	},
	{
		"title": "Beloved",
		"genre": "드라마",
		"creative_type": "역사소설",
		"source": "책",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "530",
		"us_gross": "228",
		"worldwide_gross": "228",
		"rotten_rating": "77",
		"imdb_rating": "5.3",
		"imdb_votes": "102"
	},
	{
		"title": "Big Fat Liar",
		"genre": "코미디",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "7세이상",
		"budget": "150",
		"us_gross": "478",
		"worldwide_gross": "523",
		"rotten_rating": "43",
		"imdb_rating": "5.2",
		"imdb_votes": "9,877"
	},
	{
		"title": "Blood Work",
		"genre": "스릴러",
		"creative_type": "현대소설",
		"source": "책",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "500",
		"us_gross": "261",
		"worldwide_gross": "261",
		"rotten_rating": "54",
		"imdb_rating": "6.3",
		"imdb_votes": "16,751"
	},
	{
		"title": "Bandits",
		"genre": "코미디",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "750",
		"us_gross": "415",
		"worldwide_gross": "715",
		"rotten_rating": "63",
		"imdb_rating": "6.5",
		"imdb_votes": "30,732"
	},
	{
		"title": "Boys Don't Cry",
		"genre": "드라마",
		"creative_type": "각색",
		"source": "없음",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "20",
		"us_gross": "115",
		"worldwide_gross": "207",
		"rotten_rating": "88",
		"imdb_rating": "7.6",
		"imdb_votes": "34,435"
	},
	{
		"title": "Barbershop",
		"genre": "코미디",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "120",
		"us_gross": "757",
		"worldwide_gross": "770",
		"rotten_rating": "82",
		"imdb_rating": "6.2",
		"imdb_votes": "11,164"
	},
	{
		"title": "Bulworth",
		"genre": "코미디",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "300",
		"us_gross": "265",
		"worldwide_gross": "292",
		"rotten_rating": "75",
		"imdb_rating": "6.8",
		"imdb_votes": "15,486"
	},
	{
		"title": "Bowfinger",
		"genre": "코미디",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "90년대",
		"rating": "15세이상",
		"budget": "550",
		"us_gross": "664",
		"worldwide_gross": "986",
		"rotten_rating": "79",
		"imdb_rating": "6.4",
		"imdb_votes": "33,389"
	},
	{
		"title": "Cars",
		"genre": "코미디",
		"creative_type": "아동소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "전체관람가",
		"budget": "700",
		"us_gross": "2440",
		"worldwide_gross": "4619",
		"rotten_rating": "74",
		"imdb_rating": "7.5",
		"imdb_votes": "66,809"
	},
	{
		"title": "Catch Me if You Can",
		"genre": "드라마",
		"creative_type": "각색",
		"source": "책",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "520",
		"us_gross": "1646",
		"worldwide_gross": "3511",
		"rotten_rating": "96",
		"imdb_rating": "5.7",
		"imdb_votes": "224"
	},
	{
		"title": "Crocodile Dundee in Los Angeles",
		"genre": "어드벤처",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "7세이상",
		"budget": "250",
		"us_gross": "255",
		"worldwide_gross": "393",
		"rotten_rating": "12",
		"imdb_rating": "4.6",
		"imdb_votes": "7,082"
	},
	{
		"title": "Chicken Little",
		"genre": "어드벤처",
		"creative_type": "아동소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "전체관람가",
		"budget": "600",
		"us_gross": "1353",
		"worldwide_gross": "3144",
		"rotten_rating": "36",
		"imdb_rating": "5.8",
		"imdb_votes": "17,415"
	},
	{
		"title": "Bride of Chucky",
		"genre": "호러",
		"creative_type": "판타지",
		"source": "없음",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "250",
		"us_gross": "324",
		"worldwide_gross": "506",
		"rotten_rating": "43",
		"imdb_rating": "5.3",
		"imdb_votes": "13,735"
	},
	{
		"title": "Children of Men",
		"genre": "스릴러",
		"creative_type": "공상과학",
		"source": "책",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "760",
		"us_gross": "355",
		"worldwide_gross": "694",
		"rotten_rating": "93",
		"imdb_rating": "8.1",
		"imdb_votes": "158,125"
	},
	{
		"title": "Charlotte's Web",
		"genre": "드라마",
		"creative_type": "판타지",
		"source": "책",
		"release": "2000년대",
		"rating": "전체관람가",
		"budget": "825",
		"us_gross": "829",
		"worldwide_gross": "1439",
		"rotten_rating": "78",
		"imdb_rating": "6.7",
		"imdb_votes": "8,028"
	},
	{
		"title": "The Contender",
		"genre": "드라마",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "90",
		"us_gross": "178",
		"worldwide_gross": "178",
		"rotten_rating": "76",
		"imdb_rating": "6.9",
		"imdb_votes": "13,709"
	},
	{
		"title": "Confessions of a Dangerous Mind",
		"genre": "드라마",
		"creative_type": "각색",
		"source": "책",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "290",
		"us_gross": "160",
		"worldwide_gross": "330",
		"rotten_rating": "79",
		"imdb_rating": "7.1",
		"imdb_votes": "36,258"
	},
	{
		"title": "Come Early Morning",
		"genre": "드라마",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "60",
		"us_gross": "1",
		"worldwide_gross": "1",
		"rotten_rating": "83",
		"imdb_rating": "6.2",
		"imdb_votes": "1,511"
	},
	{
		"title": "Contact",
		"genre": "드라마",
		"creative_type": "공상과학",
		"source": "책",
		"release": "90년대",
		"rating": "7세이상",
		"budget": "900",
		"us_gross": "1009",
		"worldwide_gross": "1659",
		"rotten_rating": "67",
		"imdb_rating": "7.3",
		"imdb_votes": "73,684"
	},
	{
		"title": "Crash",
		"genre": "드라마",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "65",
		"us_gross": "545",
		"worldwide_gross": "983",
		"rotten_rating": "75",
		"imdb_rating": "6.1",
		"imdb_votes": "20,886"
	},
	{
		"title": "Cruel Intentions",
		"genre": "드라마",
		"creative_type": "현대소설",
		"source": "책",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "110",
		"us_gross": "382",
		"worldwide_gross": "758",
		"rotten_rating": "47",
		"imdb_rating": "6.7",
		"imdb_votes": "66,861"
	},
	{
		"title": "Clockstoppers",
		"genre": "어드벤처",
		"creative_type": "공상과학",
		"source": "없음",
		"release": "2000년대",
		"rating": "7세이상",
		"budget": "260",
		"us_gross": "369",
		"worldwide_gross": "387",
		"rotten_rating": "28",
		"imdb_rating": "5",
		"imdb_votes": "6,392"
	},
	{
		"title": "Daredevil",
		"genre": "액션",
		"creative_type": "영웅물",
		"source": "만화",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "800",
		"us_gross": "1025",
		"worldwide_gross": "1791",
		"rotten_rating": "44",
		"imdb_rating": "5.5",
		"imdb_votes": "63,574"
	},
	{
		"title": "Donnie Darko",
		"genre": "드라마",
		"creative_type": "판타지",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "45",
		"us_gross": "12",
		"worldwide_gross": "41",
		"rotten_rating": "84",
		"imdb_rating": "8.3",
		"imdb_votes": "210,713"
	},
	{
		"title": "Date Movie",
		"genre": "코미디",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "200",
		"us_gross": "485",
		"worldwide_gross": "845",
		"rotten_rating": "6",
		"imdb_rating": "2.6",
		"imdb_votes": "31,821"
	},
	{
		"title": "Double Jeopardy",
		"genre": "액션",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "400",
		"us_gross": "1167",
		"worldwide_gross": "1778",
		"rotten_rating": "25",
		"imdb_rating": "6",
		"imdb_votes": "28,887"
	},
	{
		"title": "The Departed",
		"genre": "드라마",
		"creative_type": "현대소설",
		"source": "영화",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "900",
		"us_gross": "1333",
		"worldwide_gross": "2905",
		"rotten_rating": "93",
		"imdb_rating": "8.5",
		"imdb_votes": "264,148"
	},
	{
		"title": "Drag Me To Hell",
		"genre": "호러",
		"creative_type": "판타지",
		"source": "없음",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "300",
		"us_gross": "421",
		"worldwide_gross": "857",
		"rotten_rating": "92",
		"imdb_rating": "7.1",
		"imdb_votes": "51,343"
	},
	{
		"title": "Disturbia",
		"genre": "스릴러",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "200",
		"us_gross": "802",
		"worldwide_gross": "1175",
		"rotten_rating": "68",
		"imdb_rating": "7",
		"imdb_votes": "72,231"
	},
	{
		"title": "Death at a Funeral",
		"genre": "코미디",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "200",
		"us_gross": "85",
		"worldwide_gross": "347",
		"rotten_rating": "61",
		"imdb_rating": "5.1",
		"imdb_votes": "6,628"
	},
	{
		"title": "The Da Vinci Code",
		"genre": "스릴러",
		"creative_type": "현대소설",
		"source": "책",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "1250",
		"us_gross": "2175",
		"worldwide_gross": "7572",
		"rotten_rating": "25",
		"imdb_rating": "6.4",
		"imdb_votes": "116,903"
	},
	{
		"title": "Eagle Eye",
		"genre": "스릴러",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "800",
		"us_gross": "1014",
		"worldwide_gross": "1780",
		"rotten_rating": "27",
		"imdb_rating": "6.6",
		"imdb_votes": "52,336"
	},
	{
		"title": "8MM",
		"genre": "스릴러",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "400",
		"us_gross": "364",
		"worldwide_gross": "963",
		"rotten_rating": "22",
		"imdb_rating": "6.3",
		"imdb_votes": "47,753"
	},
	{
		"title": "The End of the Affair",
		"genre": "드라마",
		"creative_type": "역사소설",
		"source": "책",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "230",
		"us_gross": "106",
		"worldwide_gross": "106",
		"rotten_rating": "67",
		"imdb_rating": "6.9",
		"imdb_votes": "9,969"
	},
	{
		"title": "Entrapment",
		"genre": "스릴러",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "90년대",
		"rating": "15세이상",
		"budget": "660",
		"us_gross": "877",
		"worldwide_gross": "2117",
		"rotten_rating": "38",
		"imdb_rating": "6.1",
		"imdb_votes": "40,764"
	},
	{
		"title": "Enough",
		"genre": "스릴러",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "380",
		"us_gross": "391",
		"worldwide_gross": "391",
		"rotten_rating": "21",
		"imdb_rating": "6.5",
		"imdb_votes": "92"
	},
	{
		"title": "Epic Movie",
		"genre": "코미디",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "200",
		"us_gross": "397",
		"worldwide_gross": "868",
		"rotten_rating": "2",
		"imdb_rating": "2.2",
		"imdb_votes": "48,975"
	},
	{
		"title": "Event Horizon",
		"genre": "호러",
		"creative_type": "공상과학",
		"source": "없음",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "600",
		"us_gross": "266",
		"worldwide_gross": "266",
		"rotten_rating": "21",
		"imdb_rating": "6.3",
		"imdb_votes": "44,671"
	},
	{
		"title": "Extreme Ops",
		"genre": "액션",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "400",
		"us_gross": "48",
		"worldwide_gross": "126",
		"rotten_rating": "6",
		"imdb_rating": "4.1",
		"imdb_votes": "3,195"
	},
	{
		"title": "Far From Heaven",
		"genre": "드라마",
		"creative_type": "역사소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "135",
		"us_gross": "159",
		"worldwide_gross": "290",
		"rotten_rating": "89",
		"imdb_rating": "7.5",
		"imdb_votes": "20,239"
	},
	{
		"title": "Facing the Giants",
		"genre": "드라마",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "7세이상",
		"budget": "1",
		"us_gross": "101",
		"worldwide_gross": "101",
		"rotten_rating": "9",
		"imdb_rating": "6",
		"imdb_votes": "4,901"
	},
	{
		"title": "Final Destination 3",
		"genre": "호러",
		"creative_type": "판타지",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "250",
		"us_gross": "540",
		"worldwide_gross": "1127",
		"rotten_rating": "45",
		"imdb_rating": "5.9",
		"imdb_votes": "32,263"
	},
	{
		"title": "The Final Destination",
		"genre": "호러",
		"creative_type": "판타지",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "400",
		"us_gross": "664",
		"worldwide_gross": "1857",
		"rotten_rating": "27",
		"imdb_rating": "4.9",
		"imdb_votes": "20,319"
	},
	{
		"title": "From Hell",
		"genre": "스릴러",
		"creative_type": "역사소설",
		"source": "만화",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "350",
		"us_gross": "315",
		"worldwide_gross": "315",
		"rotten_rating": "57",
		"imdb_rating": "6.8",
		"imdb_votes": "53,477"
	},
	{
		"title": "Fight Club",
		"genre": "드라마",
		"creative_type": "현대소설",
		"source": "책",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "650",
		"us_gross": "370",
		"worldwide_gross": "1008",
		"rotten_rating": "81",
		"imdb_rating": "8.8",
		"imdb_votes": "382,470"
	},
	{
		"title": "Finding Forrester",
		"genre": "드라마",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "430",
		"us_gross": "517",
		"worldwide_gross": "800",
		"rotten_rating": "74",
		"imdb_rating": "7.2",
		"imdb_votes": "35,966"
	},
	{
		"title": "Flubber",
		"genre": "코미디",
		"creative_type": "아동소설",
		"source": "영화",
		"release": "90년대",
		"rating": "7세이상",
		"budget": "800",
		"us_gross": "929",
		"worldwide_gross": "1779",
		"rotten_rating": "17",
		"imdb_rating": "4.6",
		"imdb_votes": "18,890"
	},
	{
		"title": "Flushed Away",
		"genre": "코미디",
		"creative_type": "아동소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "7세이상",
		"budget": "1490",
		"us_gross": "646",
		"worldwide_gross": "1776",
		"rotten_rating": "72",
		"imdb_rating": "7",
		"imdb_votes": "21,334"
	},
	{
		"title": "Friday Night Lights",
		"genre": "드라마",
		"creative_type": "현대소설",
		"source": "책",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "300",
		"us_gross": "612",
		"worldwide_gross": "619",
		"rotten_rating": "81",
		"imdb_rating": "7.2",
		"imdb_votes": "20,868"
	},
	{
		"title": "The Princess and the Frog",
		"genre": "어드벤처",
		"creative_type": "아동소설",
		"source": "책",
		"release": "2000년대",
		"rating": "전체관람가",
		"budget": "1050",
		"us_gross": "1043",
		"worldwide_gross": "2634",
		"rotten_rating": "84",
		"imdb_rating": "7.4",
		"imdb_votes": "16,232"
	},
	{
		"title": "Fireproof",
		"genre": "드라마",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "7세이상",
		"budget": "5",
		"us_gross": "334",
		"worldwide_gross": "334",
		"rotten_rating": "40",
		"imdb_rating": "5.6",
		"imdb_votes": "5,498"
	},
	{
		"title": "For Your Consideration",
		"genre": "코미디",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "120",
		"us_gross": "55",
		"worldwide_gross": "55",
		"rotten_rating": "50",
		"imdb_rating": "6.2",
		"imdb_votes": "7,780"
	},
	{
		"title": "The Game",
		"genre": "스릴러",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "500",
		"us_gross": "482",
		"worldwide_gross": "482",
		"rotten_rating": "80",
		"imdb_rating": "7.7",
		"imdb_votes": "74,136"
	},
	{
		"title": "The General's Daughter",
		"genre": "드라마",
		"creative_type": "현대소설",
		"source": "책",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "600",
		"us_gross": "1027",
		"worldwide_gross": "1497",
		"rotten_rating": "22",
		"imdb_rating": "6.1",
		"imdb_votes": "23,570"
	},
	{
		"title": "Garden State",
		"genre": "드라마",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "25",
		"us_gross": "267",
		"worldwide_gross": "323",
		"rotten_rating": "86",
		"imdb_rating": "7.9",
		"imdb_votes": "92,594"
	},
	{
		"title": "How the Grinch Stole Christmas",
		"genre": "코미디",
		"creative_type": "아동소설",
		"source": "책",
		"release": "2000년대",
		"rating": "7세이상",
		"budget": "1230",
		"us_gross": "2600",
		"worldwide_gross": "3451",
		"rotten_rating": "53",
		"imdb_rating": "5.7",
		"imdb_votes": "40,310"
	},
	{
		"title": "The Happening",
		"genre": "스릴러",
		"creative_type": "공상과학",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "600",
		"us_gross": "645",
		"worldwide_gross": "1634",
		"rotten_rating": "18",
		"imdb_rating": "5.2",
		"imdb_votes": "72,259"
	},
	{
		"title": "Heist",
		"genre": "액션",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "350",
		"us_gross": "234",
		"worldwide_gross": "284",
		"rotten_rating": "66",
		"imdb_rating": "3.2",
		"imdb_votes": "77"
	},
	{
		"title": "The Haunting",
		"genre": "호러",
		"creative_type": "현대소설",
		"source": "책",
		"release": "90년대",
		"rating": "15세이상",
		"budget": "800",
		"us_gross": "911",
		"worldwide_gross": "1801",
		"rotten_rating": "17",
		"imdb_rating": "4.6",
		"imdb_votes": "31,808"
	},
	{
		"title": "The Hills Have Eyes",
		"genre": "호러",
		"creative_type": "현대소설",
		"source": "영화",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "170",
		"us_gross": "417",
		"worldwide_gross": "696",
		"rotten_rating": "49",
		"imdb_rating": "6.5",
		"imdb_votes": "43,747"
	},
	{
		"title": "Holes",
		"genre": "드라마",
		"creative_type": "현대소설",
		"source": "책",
		"release": "2000년대",
		"rating": "7세이상",
		"budget": "200",
		"us_gross": "673",
		"worldwide_gross": "723",
		"rotten_rating": "77",
		"imdb_rating": "7.1",
		"imdb_votes": "19,388"
	},
	{
		"title": "Hollow Man",
		"genre": "호러",
		"creative_type": "공상과학",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "900",
		"us_gross": "732",
		"worldwide_gross": "1912",
		"rotten_rating": "28",
		"imdb_rating": "5.5",
		"imdb_votes": "41,499"
	},
	{
		"title": "Harry Potter and the Chamber of Secrets",
		"genre": "어드벤처",
		"creative_type": "판타지",
		"source": "책",
		"release": "2000년대",
		"rating": "7세이상",
		"budget": "1000",
		"us_gross": "2619",
		"worldwide_gross": "8789",
		"rotten_rating": "82",
		"imdb_rating": "7.2",
		"imdb_votes": "120,063"
	},
	{
		"title": "Inkheart",
		"genre": "어드벤처",
		"creative_type": "판타지",
		"source": "책",
		"release": "2000년대",
		"rating": "7세이상",
		"budget": "600",
		"us_gross": "173",
		"worldwide_gross": "580",
		"rotten_rating": "40",
		"imdb_rating": "6.1",
		"imdb_votes": "14,157"
	},
	{
		"title": "In & Out",
		"genre": "코미디",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "90년대",
		"rating": "15세이상",
		"budget": "350",
		"us_gross": "638",
		"worldwide_gross": "832",
		"rotten_rating": "71",
		"imdb_rating": "6.1",
		"imdb_votes": "18,773"
	},
	{
		"title": "The Insider",
		"genre": "드라마",
		"creative_type": "각색",
		"source": "책",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "680",
		"us_gross": "289",
		"worldwide_gross": "602",
		"rotten_rating": "96",
		"imdb_rating": "8",
		"imdb_votes": "68,747"
	},
	{
		"title": "Iron Man",
		"genre": "액션",
		"creative_type": "영웅물",
		"source": "만화",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "1860",
		"us_gross": "3186",
		"worldwide_gross": "5826",
		"rotten_rating": "94",
		"imdb_rating": "7.9",
		"imdb_votes": "174,040"
	},
	{
		"title": "Die Another Day",
		"genre": "액션",
		"creative_type": "현대소설",
		"source": "책",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "1420",
		"us_gross": "1609",
		"worldwide_gross": "4319",
		"rotten_rating": "59",
		"imdb_rating": "6",
		"imdb_votes": "67,476"
	},
	{
		"title": "Casino Royale",
		"genre": "액션",
		"creative_type": "현대소설",
		"source": "책",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "1020",
		"us_gross": "1673",
		"worldwide_gross": "5963",
		"rotten_rating": "94",
		"imdb_rating": "8",
		"imdb_votes": "172,936"
	},
	{
		"title": "Quantum of Solace",
		"genre": "액션",
		"creative_type": "현대소설",
		"source": "책",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "2300",
		"us_gross": "1693",
		"worldwide_gross": "5763",
		"rotten_rating": "64",
		"imdb_rating": "6.8",
		"imdb_votes": "93,596"
	},
	{
		"title": "Julie & Julia",
		"genre": "코미디",
		"creative_type": "현대소설",
		"source": "책",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "400",
		"us_gross": "941",
		"worldwide_gross": "1266",
		"rotten_rating": "75",
		"imdb_rating": "7.2",
		"imdb_votes": "22,269"
	},
	{
		"title": "Kiss of the Dragon",
		"genre": "액션",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "250",
		"us_gross": "368",
		"worldwide_gross": "368",
		"rotten_rating": "51",
		"imdb_rating": "6.3",
		"imdb_votes": "22,087"
	},
	{
		"title": "Kill Bill: Volume 1",
		"genre": "액션",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "550",
		"us_gross": "700",
		"worldwide_gross": "1800",
		"rotten_rating": "85",
		"imdb_rating": "8.2",
		"imdb_votes": "231,761"
	},
	{
		"title": "Kingdom of Heaven",
		"genre": "어드벤처",
		"creative_type": "역사소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "1100",
		"us_gross": "473",
		"worldwide_gross": "2113",
		"rotten_rating": "39",
		"imdb_rating": "7.1",
		"imdb_votes": "83,189"
	},
	{
		"title": "Knowing",
		"genre": "스릴러",
		"creative_type": "현대소설",
		"source": "책",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "500",
		"us_gross": "799",
		"worldwide_gross": "1878",
		"rotten_rating": "32",
		"imdb_rating": "6.4",
		"imdb_votes": "58,138"
	},
	{
		"title": "K-PAX",
		"genre": "드라마",
		"creative_type": "공상과학",
		"source": "책",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "480",
		"us_gross": "503",
		"worldwide_gross": "503",
		"rotten_rating": "40",
		"imdb_rating": "7.3",
		"imdb_votes": "50,475"
	},
	{
		"title": "King's Ransom",
		"genre": "코미디",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "250",
		"us_gross": "40",
		"worldwide_gross": "40",
		"rotten_rating": "2",
		"imdb_rating": "3.5",
		"imdb_votes": "2,251"
	},
	{
		"title": "Kundun",
		"genre": "드라마",
		"creative_type": "각색",
		"source": "없음",
		"release": "90년대",
		"rating": "15세이상",
		"budget": "280",
		"us_gross": "56",
		"worldwide_gross": "56",
		"rotten_rating": "76",
		"imdb_rating": "7",
		"imdb_votes": "10,248"
	},
	{
		"title": "Ladder 49",
		"genre": "액션",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "600",
		"us_gross": "745",
		"worldwide_gross": "1023",
		"rotten_rating": "40",
		"imdb_rating": "6.5",
		"imdb_votes": "23,369"
	},
	{
		"title": "The Life Aquatic with Steve Zissou",
		"genre": "코미디",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "500",
		"us_gross": "240",
		"worldwide_gross": "348",
		"rotten_rating": "53",
		"imdb_rating": "7.2",
		"imdb_votes": "57,889"
	},
	{
		"title": "Like Mike",
		"genre": "코미디",
		"creative_type": "아동소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "7세이상",
		"budget": "300",
		"us_gross": "514",
		"worldwide_gross": "624",
		"rotten_rating": "56",
		"imdb_rating": "4.4",
		"imdb_votes": "4,870"
	},
	{
		"title": "Lord of War",
		"genre": "액션",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "420",
		"us_gross": "241",
		"worldwide_gross": "621",
		"rotten_rating": "61",
		"imdb_rating": "7.7",
		"imdb_votes": "80,124"
	},
	{
		"title": "The Last Samurai",
		"genre": "액션",
		"creative_type": "역사소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "1200",
		"us_gross": "1111",
		"worldwide_gross": "4568",
		"rotten_rating": "65",
		"imdb_rating": "7.8",
		"imdb_votes": "106,002"
	},
	{
		"title": "Mad City",
		"genre": "드라마",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "90년대",
		"rating": "15세이상",
		"budget": "500",
		"us_gross": "105",
		"worldwide_gross": "105",
		"rotten_rating": "37",
		"imdb_rating": "6.1",
		"imdb_votes": "9,611"
	},
	{
		"title": "Paul Blart: Mall Cop",
		"genre": "코미디",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "7세이상",
		"budget": "260",
		"us_gross": "1463",
		"worldwide_gross": "1804",
		"rotten_rating": "35",
		"imdb_rating": "5.3",
		"imdb_votes": "23,753"
	},
	{
		"title": "Marci X",
		"genre": "코미디",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "200",
		"us_gross": "16",
		"worldwide_gross": "16",
		"rotten_rating": "10",
		"imdb_rating": "2.4",
		"imdb_votes": "3,449"
	},
	{
		"title": "Meet Joe Black",
		"genre": "드라마",
		"creative_type": "판타지",
		"source": "없음",
		"release": "90년대",
		"rating": "15세이상",
		"budget": "850",
		"us_gross": "446",
		"worldwide_gross": "446",
		"rotten_rating": "50",
		"imdb_rating": "6.9",
		"imdb_votes": "56,067"
	},
	{
		"title": "Mindhunters",
		"genre": "스릴러",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "270",
		"us_gross": "44",
		"worldwide_gross": "165",
		"rotten_rating": "26",
		"imdb_rating": "6.2",
		"imdb_votes": "23,357"
	},
	{
		"title": "Captain Corelli's Mandolin",
		"genre": "드라마",
		"creative_type": "역사소설",
		"source": "책",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "570",
		"us_gross": "255",
		"worldwide_gross": "620",
		"rotten_rating": "29",
		"imdb_rating": "5.7",
		"imdb_votes": "14,706"
	},
	{
		"title": "Moonlight Mile",
		"genre": "드라마",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "210",
		"us_gross": "68",
		"worldwide_gross": "68",
		"rotten_rating": "62",
		"imdb_rating": "6.7",
		"imdb_votes": "8,346"
	},
	{
		"title": "Me and Orson Welles",
		"genre": "드라마",
		"creative_type": "역사소설",
		"source": "책",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "250",
		"us_gross": "11",
		"worldwide_gross": "11",
		"rotten_rating": "84",
		"imdb_rating": "7.1",
		"imdb_votes": "2,417"
	},
	{
		"title": "Meet the Spartans",
		"genre": "코미디",
		"creative_type": "역사소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "300",
		"us_gross": "382",
		"worldwide_gross": "846",
		"rotten_rating": "2",
		"imdb_rating": "2.4",
		"imdb_votes": "47,281"
	},
	{
		"title": "The Matrix Reloaded",
		"genre": "액션",
		"creative_type": "공상과학",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "1270",
		"us_gross": "2815",
		"worldwide_gross": "7385",
		"rotten_rating": "73",
		"imdb_rating": "7.1",
		"imdb_votes": "148,874"
	},
	{
		"title": "Murder by Numbers",
		"genre": "스릴러",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "500",
		"us_gross": "318",
		"worldwide_gross": "566",
		"rotten_rating": "31",
		"imdb_rating": "5.9",
		"imdb_votes": "22,318"
	},
	{
		"title": "The Muse",
		"genre": "코미디",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "90년대",
		"rating": "15세이상",
		"budget": "150",
		"us_gross": "116",
		"worldwide_gross": "116",
		"rotten_rating": "51",
		"imdb_rating": "5.5",
		"imdb_votes": "6,507"
	},
	{
		"title": "Night at the Museum",
		"genre": "코미디",
		"creative_type": "판타지",
		"source": "책",
		"release": "2000년대",
		"rating": "7세이상",
		"budget": "1100",
		"us_gross": "2508",
		"worldwide_gross": "5744",
		"rotten_rating": "43",
		"imdb_rating": "6.4",
		"imdb_votes": "67,133"
	},
	{
		"title": "Monsters vs. Aliens",
		"genre": "어드벤처",
		"creative_type": "판타지",
		"source": "만화",
		"release": "2000년대",
		"rating": "7세이상",
		"budget": "1750",
		"us_gross": "1983",
		"worldwide_gross": "3816",
		"rotten_rating": "72",
		"imdb_rating": "6.8",
		"imdb_votes": "26,582"
	},
	{
		"title": "A Mighty Wind",
		"genre": "코미디",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "60",
		"us_gross": "175",
		"worldwide_gross": "185",
		"rotten_rating": "88",
		"imdb_rating": "7.2",
		"imdb_votes": "13,602"
	},
	{
		"title": "My Dog Skip",
		"genre": "드라마",
		"creative_type": "아동소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "7세이상",
		"budget": "70",
		"us_gross": "340",
		"worldwide_gross": "355",
		"rotten_rating": "72",
		"imdb_rating": "6.9",
		"imdb_votes": "9,029"
	},
	{
		"title": "My Fellow Americans",
		"genre": "코미디",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "90년대",
		"rating": "15세이상",
		"budget": "215",
		"us_gross": "223",
		"worldwide_gross": "223",
		"rotten_rating": "50",
		"imdb_rating": "6.3",
		"imdb_votes": "6,366"
	},
	{
		"title": "The Nativity Story",
		"genre": "드라마",
		"creative_type": "각색",
		"source": "책",
		"release": "2000년대",
		"rating": "7세이상",
		"budget": "350",
		"us_gross": "376",
		"worldwide_gross": "464",
		"rotten_rating": "37",
		"imdb_rating": "6.6",
		"imdb_votes": "4,701"
	},
	{
		"title": "In Good Company",
		"genre": "코미디",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "260",
		"us_gross": "454",
		"worldwide_gross": "634",
		"rotten_rating": "84",
		"imdb_rating": "6.8",
		"imdb_votes": "25,695"
	},
	{
		"title": "Lucky Numbers",
		"genre": "코미디",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "650",
		"us_gross": "100",
		"worldwide_gross": "100",
		"rotten_rating": "23",
		"imdb_rating": "4.9",
		"imdb_votes": "5,461"
	},
	{
		"title": "The Interpreter",
		"genre": "스릴러",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "900",
		"us_gross": "727",
		"worldwide_gross": "1639",
		"rotten_rating": "58",
		"imdb_rating": "6.5",
		"imdb_votes": "38,227"
	},
	{
		"title": "The Number 23",
		"genre": "스릴러",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "320",
		"us_gross": "351",
		"worldwide_gross": "765",
		"rotten_rating": "8",
		"imdb_rating": "6.2",
		"imdb_votes": "59,174"
	},
	{
		"title": "The New World",
		"genre": "어드벤처",
		"creative_type": "역사소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "300",
		"us_gross": "127",
		"worldwide_gross": "261",
		"rotten_rating": "60",
		"imdb_rating": "6.9",
		"imdb_votes": "33,248"
	},
	{
		"title": "Ocean's Eleven",
		"genre": "코미디",
		"creative_type": "현대소설",
		"source": "영화",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "1100",
		"us_gross": "1834",
		"worldwide_gross": "4507",
		"rotten_rating": "81",
		"imdb_rating": "7.6",
		"imdb_votes": "139,034"
	},
	{
		"title": "Old School",
		"genre": "코미디",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "240",
		"us_gross": "751",
		"worldwide_gross": "863",
		"rotten_rating": "60",
		"imdb_rating": "7",
		"imdb_votes": "60,477"
	},
	{
		"title": "Out of Time",
		"genre": "스릴러",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "500",
		"us_gross": "410",
		"worldwide_gross": "554",
		"rotten_rating": "65",
		"imdb_rating": "4.9",
		"imdb_votes": "151"
	},
	{
		"title": "The Passion of the Christ",
		"genre": "드라마",
		"creative_type": "각색",
		"source": "책",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "250",
		"us_gross": "3707",
		"worldwide_gross": "6118",
		"rotten_rating": "50",
		"imdb_rating": "7.1",
		"imdb_votes": "87,326"
	},
	{
		"title": "A Perfect Getaway",
		"genre": "스릴러",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "140",
		"us_gross": "155",
		"worldwide_gross": "206",
		"rotten_rating": "60",
		"imdb_rating": "6.5",
		"imdb_votes": "16,324"
	},
	{
		"title": "The Chronicles of Riddick",
		"genre": "어드벤처",
		"creative_type": "공상과학",
		"source": "없음",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "1200",
		"us_gross": "577",
		"worldwide_gross": "1072",
		"rotten_rating": "29",
		"imdb_rating": "6.4",
		"imdb_votes": "49,383"
	},
	{
		"title": "Planet of the Apes",
		"genre": "어드벤처",
		"creative_type": "공상과학",
		"source": "영화",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "1000",
		"us_gross": "1800",
		"worldwide_gross": "3622",
		"rotten_rating": "44",
		"imdb_rating": "5.5",
		"imdb_votes": "72,763"
	},
	{
		"title": "Possession",
		"genre": "드라마",
		"creative_type": "현대소설",
		"source": "책",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "250",
		"us_gross": "101",
		"worldwide_gross": "148",
		"rotten_rating": "64",
		"imdb_rating": "6.4",
		"imdb_votes": "6,789"
	},
	{
		"title": "Practical Magic",
		"genre": "코미디",
		"creative_type": "판타지",
		"source": "책",
		"release": "90년대",
		"rating": "15세이상",
		"budget": "600",
		"us_gross": "468",
		"worldwide_gross": "683",
		"rotten_rating": "21",
		"imdb_rating": "5.5",
		"imdb_votes": "20,196"
	},
	{
		"title": "Quarantine",
		"genre": "호러",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "120",
		"us_gross": "316",
		"worldwide_gross": "360",
		"rotten_rating": "58",
		"imdb_rating": "6.1",
		"imdb_votes": "21,939"
	},
	{
		"title": "Rabbit-Proof Fence",
		"genre": "드라마",
		"creative_type": "역사소설",
		"source": "책",
		"release": "2000년대",
		"rating": "7세이상",
		"budget": "70",
		"us_gross": "61",
		"worldwide_gross": "161",
		"rotten_rating": "87",
		"imdb_rating": "7.6",
		"imdb_votes": "13,241"
	},
	{
		"title": "Ratatouille",
		"genre": "코미디",
		"creative_type": "판타지",
		"source": "없음",
		"release": "2000년대",
		"rating": "전체관람가",
		"budget": "1500",
		"us_gross": "2064",
		"worldwide_gross": "6204",
		"rotten_rating": "96",
		"imdb_rating": "8.1",
		"imdb_votes": "131,929"
	},
	{
		"title": "Robots",
		"genre": "어드벤처",
		"creative_type": "아동소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "7세이상",
		"budget": "800",
		"us_gross": "1282",
		"worldwide_gross": "2607",
		"rotten_rating": "64",
		"imdb_rating": "6.4",
		"imdb_votes": "27,361"
	},
	{
		"title": "Red Dragon",
		"genre": "스릴러",
		"creative_type": "현대소설",
		"source": "책",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "780",
		"us_gross": "929",
		"worldwide_gross": "2064",
		"rotten_rating": "68",
		"imdb_rating": "7.3",
		"imdb_votes": "66,386"
	},
	{
		"title": "The Reader",
		"genre": "드라마",
		"creative_type": "현대소설",
		"source": "책",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "330",
		"us_gross": "341",
		"worldwide_gross": "1061",
		"rotten_rating": "61",
		"imdb_rating": "7.7",
		"imdb_votes": "46,984"
	},
	{
		"title": "The Rocker",
		"genre": "코미디",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "150",
		"us_gross": "64",
		"worldwide_gross": "87",
		"rotten_rating": "40",
		"imdb_rating": "6.3",
		"imdb_votes": "11,859"
	},
	{
		"title": "Rock Star",
		"genre": "드라마",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "380",
		"us_gross": "169",
		"worldwide_gross": "193",
		"rotten_rating": "52",
		"imdb_rating": "5.8",
		"imdb_votes": "15,806"
	},
	{
		"title": "Romeo Must Die",
		"genre": "액션",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "250",
		"us_gross": "559",
		"worldwide_gross": "910",
		"rotten_rating": "33",
		"imdb_rating": "5.9",
		"imdb_votes": "25,309"
	},
	{
		"title": "Road Trip",
		"genre": "코미디",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "160",
		"us_gross": "685",
		"worldwide_gross": "1197",
		"rotten_rating": "59",
		"imdb_rating": "6.4",
		"imdb_votes": "44,702"
	},
	{
		"title": "Rules of Engagement",
		"genre": "스릴러",
		"creative_type": "현대소설",
		"source": "책",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "600",
		"us_gross": "613",
		"worldwide_gross": "717",
		"rotten_rating": "37",
		"imdb_rating": "6.2",
		"imdb_votes": "18,462"
	},
	{
		"title": "Rush Hour 2",
		"genre": "액션",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "900",
		"us_gross": "2261",
		"worldwide_gross": "3474",
		"rotten_rating": "51",
		"imdb_rating": "6.4",
		"imdb_votes": "52,049"
	},
	{
		"title": "Saw VI",
		"genre": "호러",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "110",
		"us_gross": "276",
		"worldwide_gross": "612",
		"rotten_rating": "42",
		"imdb_rating": "6.2",
		"imdb_votes": "18,091"
	},
	{
		"title": "About Schmidt",
		"genre": "드라마",
		"creative_type": "현대소설",
		"source": "책",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "300",
		"us_gross": "650",
		"worldwide_gross": "1058",
		"rotten_rating": "85",
		"imdb_rating": "7.3",
		"imdb_votes": "53,760"
	},
	{
		"title": "Shutter Island",
		"genre": "스릴러",
		"creative_type": "역사소설",
		"source": "책",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "800",
		"us_gross": "1280",
		"worldwide_gross": "2945",
		"rotten_rating": "67",
		"imdb_rating": "8",
		"imdb_votes": "105,706"
	},
	{
		"title": "Shrek",
		"genre": "어드벤처",
		"creative_type": "아동소설",
		"source": "책",
		"release": "2000년대",
		"rating": "7세이상",
		"budget": "500",
		"us_gross": "2676",
		"worldwide_gross": "4843",
		"rotten_rating": "89",
		"imdb_rating": "8",
		"imdb_votes": "163,855"
	},
	{
		"title": "Shrek 2",
		"genre": "어드벤처",
		"creative_type": "아동소설",
		"source": "책",
		"release": "2000년대",
		"rating": "7세이상",
		"budget": "700",
		"us_gross": "4412",
		"worldwide_gross": "9198",
		"rotten_rating": "89",
		"imdb_rating": "7.5",
		"imdb_votes": "95,658"
	},
	{
		"title": "The Sixth Sense",
		"genre": "스릴러",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "90년대",
		"rating": "15세이상",
		"budget": "400",
		"us_gross": "2935",
		"worldwide_gross": "6728",
		"rotten_rating": "85",
		"imdb_rating": "8.2",
		"imdb_votes": "238,745"
	},
	{
		"title": "The Skeleton Key",
		"genre": "호러",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "400",
		"us_gross": "479",
		"worldwide_gross": "929",
		"rotten_rating": "38",
		"imdb_rating": "6.5",
		"imdb_votes": "29,810"
	},
	{
		"title": "Sleepy Hollow",
		"genre": "호러",
		"creative_type": "역사소설",
		"source": "책",
		"release": "90년대",
		"rating": "19세이상",
		"budget": "700",
		"us_gross": "1010",
		"worldwide_gross": "2070",
		"rotten_rating": "68",
		"imdb_rating": "7.5",
		"imdb_votes": "107,511"
	},
	{
		"title": "Superbad",
		"genre": "코미디",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "175",
		"us_gross": "1214",
		"worldwide_gross": "1698",
		"rotten_rating": "87",
		"imdb_rating": "7.8",
		"imdb_votes": "134,212"
	},
	{
		"title": "Superman Returns",
		"genre": "어드벤처",
		"creative_type": "영웅물",
		"source": "만화",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "2320",
		"us_gross": "2001",
		"worldwide_gross": "3911",
		"rotten_rating": "76",
		"imdb_rating": "6.6",
		"imdb_votes": "102,751"
	},
	{
		"title": "Small Time Crooks",
		"genre": "코미디",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "7세이상",
		"budget": "180",
		"us_gross": "172",
		"worldwide_gross": "299",
		"rotten_rating": "66",
		"imdb_rating": "6.5",
		"imdb_votes": "15,636"
	},
	{
		"title": "Stepmom",
		"genre": "드라마",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "90년대",
		"rating": "15세이상",
		"budget": "500",
		"us_gross": "911",
		"worldwide_gross": "1197",
		"rotten_rating": "43",
		"imdb_rating": "6.2",
		"imdb_votes": "18,505"
	},
	{
		"title": "The Perfect Storm",
		"genre": "드라마",
		"creative_type": "각색",
		"source": "책",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "1200",
		"us_gross": "1826",
		"worldwide_gross": "3287",
		"rotten_rating": "47",
		"imdb_rating": "6.2",
		"imdb_votes": "55,716"
	},
	{
		"title": "Tadpole",
		"genre": "코미디",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "1",
		"us_gross": "28",
		"worldwide_gross": "32",
		"rotten_rating": "78",
		"imdb_rating": "6.1",
		"imdb_votes": "3,800"
	},
	{
		"title": "The Tale of Despereaux",
		"genre": "어드벤처",
		"creative_type": "아동소설",
		"source": "책",
		"release": "2000년대",
		"rating": "전체관람가",
		"budget": "600",
		"us_gross": "508",
		"worldwide_gross": "887",
		"rotten_rating": "55",
		"imdb_rating": "6.1",
		"imdb_votes": "7,460"
	},
	{
		"title": "Tears of the Sun",
		"genre": "액션",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "750",
		"us_gross": "436",
		"worldwide_gross": "856",
		"rotten_rating": "34",
		"imdb_rating": "6.4",
		"imdb_votes": "34,304"
	},
	{
		"title": "The Box",
		"genre": "스릴러",
		"creative_type": "판타지",
		"source": "책",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "250",
		"us_gross": "150",
		"worldwide_gross": "263",
		"rotten_rating": "45",
		"imdb_rating": "6.8",
		"imdb_votes": "418"
	},
	{
		"title": "The League of Extraordinary Gentlemen",
		"genre": "어드벤처",
		"creative_type": "영웅물",
		"source": "만화",
		"release": "2000년대",
		"rating": "15세이상",
		"budget": "780",
		"us_gross": "664",
		"worldwide_gross": "1792",
		"rotten_rating": "17",
		"imdb_rating": "5.5",
		"imdb_votes": "50,710"
	},
	{
		"title": "The Mist",
		"genre": "호러",
		"creative_type": "공상과학",
		"source": "책",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "130",
		"us_gross": "255",
		"worldwide_gross": "547",
		"rotten_rating": "73",
		"imdb_rating": "7.4",
		"imdb_votes": "76,830"
	},
	{
		"title": "Tomorrow Never Dies",
		"genre": "액션",
		"creative_type": "현대소설",
		"source": "책",
		"release": "90년대",
		"rating": "15세이상",
		"budget": "1100",
		"us_gross": "1253",
		"worldwide_gross": "3395",
		"rotten_rating": "55",
		"imdb_rating": "6.4",
		"imdb_votes": "46,650"
	},
	{
		"title": "The Town",
		"genre": "드라마",
		"creative_type": "현대소설",
		"source": "책",
		"release": "2000년대",
		"rating": "19세이상",
		"budget": "370",
		"us_gross": "309",
		"worldwide_gross": "331",
		"rotten_rating": "84",
		"imdb_rating": "8.7",
		"imdb_votes": "493"
	}
]